name: CI
on:
  pull_request:
    branches:
      - develop
      - 'release/**'
  env:
    CTP_CLIENT_SECRET: ${{ secrets.CTP_CLIENT_SECRET }}
    CTP_CLIENT_ID: ${{ secrets.CTP_CLIENT_ID }}
    CTP_SCOPES: ${{ secrets.CTP_SCOPES }}
    CLIENT_CLIENT_SECRET: ${{ secrets.CLIENT_CLIENT_SECRET }}
    CLIENT_CLIENT_ID: ${{ secrets.CLIENT_CLIENT_ID }}
    CLIENT_SCOPES: ${{ secrets.CLIENT_SCOPES }}
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Get repo code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Cache dependencies
        id: cache-node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node_modules-

      - name: Install dependencies
        if: steps.cache-node_modules.outputs.cache-hit != 'true'
        run: npm ci

      - name: Format code with Prettier
        run: npm run format

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Cache dependencies
        id: cache-node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node_modules-

      - name: Install dependencies
        if: steps.cache-node_modules.outputs.cache-hit != 'true'
        run: npm ci

      - name: Run tests
        run: npm run lint

  test:
    needs: [ lint, format ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Cache dependencies
        id: cache-node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node_modules-

      - name: Install dependencies
        if: steps.cache-node_modules.outputs.cache-hit != 'true'
        run: npm ci

      - name: Run tests
        run: npm run test

      - name: Get report
        run: npm run coverage
